### ISSUE TITLE
Where download augmentation data?

### ISSUE THREAD

**Issue by yumaru0520** [MSiam/AdaptiveMaskedProxies#15]
Hello
Thanks a lot for sharing the code. 

Now I try to run 
`python train.py --config configs/fcn8s_pascal.yml`.
But an error occurred.

`python train.py --config configs/fcn8s_pascal.yml
train.py:246: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg = yaml.load(fp)
RUNDIR: runs/fcn8s_pascal/66314
Pre-encoding segmentation masks...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 10582/10582 [00:00<00:00, 341287.71it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 10582/10582 [01:26<00:00, 123.02it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 1449/1449 [01:23<00:00, 17.43it/s]
Pre-encoding segmentation masks...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 10582/10582 [00:00<00:00, 348203.64it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 10582/10582 [01:24<00:00, 125.91it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 1449/1449 [01:24<00:00, 17.25it/s]
Traceback (most recent call last):
  File "train.py", line 258, in <module>
    train(cfg, writer, logger)
  File "train.py", line 140, in train
    original_sprt_images, original_qry_images, cls_ind) in trainloader:
  File "/home/yumaru/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/yumaru/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/yumaru/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yumaru/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yumaru/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yumaru/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yumaru/Documents/project/AdaptiveMaskedProxies-master/ptsemseg/loader/pascal_voc_loader.py", line 105, in __getitem__
    lbl = Image.open(lbl_path)
  File "/home/yumaru/anaconda3/lib/python3.7/site-packages/PIL/Image.py", line 2770, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../data/VOCdevkit/VOC2012/SegmentationClass/pre_encoded_0/2010_003077.png'
`

I think I'm getting an error because I don't have enough data.
VOCdevkit/VOC2012/SegmentationClass : 2913 images
datasets/train_aug.txt : 10582 rows (images).

Where download augmentation data?

**Comment by Alex-dong** [comment]
did you solve this problem ? i think i meet the same one

**Comment by carrierlxk** [comment]
I have met the same issue, did you solve it?
